version: '3.7'

services:
  signup-app:
    container_name: signup-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8082:8080'